In [110]:
import csv
import pandas as pd
import random
import torch


In [165]:
input_node_num = 16
input_num_mul_index = 16 #  把输入维度放大10倍

# input_node_num = input_node_num * input_num_mul #  把输入维度放大10倍

def ysc_create_data_before_pretrain_new_new():
    rows = 10000
    data = []
    groups = {
        'ANGRY': [15, 11],
        'NEGATIVE': [14, 10, 7, 6, 5, 3, 1], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
        'POSITIVE': [2, 9, 10, 13],
        'NULL': [0, 4, 8, 12]
        }
    for _ in range(rows):
        selected_group = random.choice(list(groups.values()))
        result_list = [0.0] * input_node_num
        for i in range(input_node_num):
            if i in selected_group:
                result_list[i] = 1.0
            else:
                result_list[i] = random.uniform(0, 0.2)
        data.append(result_list * input_num_mul_index)
    with open('output.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(data)
    print("CSV文件已保存。")


In [167]:
df = pd.read_csv('output.csv', header=None) # 读取数据

In [170]:
data = df.values.tolist()

In [176]:

data[0][:16]

[0.0391732143703741,
 1.0,
 0.0555095161070095,
 1.0,
 0.0945372762556412,
 1.0,
 1.0,
 1.0,
 0.1009463541774024,
 0.0567735630339054,
 1.0,
 0.093299828365135,
 0.053613880015351,
 0.1722589185979061,
 1.0,
 0.0683625065090262]

In [163]:
ls = [1,2,3,4,5,6]
ls2 = ls * 2

In [164]:
ls2[0]= 100
ls2

[100, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [166]:
ysc_create_data_before_pretrain_new_new()


CSV文件已保存。


In [ ]:
buffer = torch.load('ysc_buffer.pth')

In [ ]:
torch.tensor(0).unsqueeze(0)

In [ ]:
avg_buffer = [sum(buffer[i][-100:]) / len(buffer[i][-100:]) for i in range(len(buffer))]

In [ ]:
buffer.shape

In [ ]:
len(buffer[1])

In [ ]:
buffer = torch.load('ysc_buffer.pth')
len(buffer)

In [ ]:
for i in range(4):
    print(len(buffer[i]))

In [ ]:
[sum(buffer[i][-200:]) / len(buffer[i][-200:]) for i in range(len(buffer))]

In [ ]:
ls = [[] for _ in range(4)]

In [ ]:
a = torch.randn(2,13)
b = torch.randn(2,13)
a / b

In [ ]:
import numpy as np

In [ ]:
np.random.rand(10, 4) * 0.2

In [ ]:
a = torch.load('weight_origin.pth')

In [ ]:
a


In [ ]:
b = torch.load('weight_new.pth')

In [ ]:
b

In [ ]:
a[0][9]

In [ ]:
b[0][9]

In [ ]:
for i in range(c.shape[0]):
    if all(c[i]) :
        pass
    else:
        print(i)

In [ ]:
all(c[10])
c[10]

In [ ]:
ls1 = [1,2,3,4]
ls2 = [1,2,3,4]

In [ ]:
torch.tensor(ls1) / torch.tensor(ls2)

In [ ]:
dw = torch.load('dw.pth')
dw

In [88]:
dw = torch.load('dw.pth')
for i  in range(dw.shape[0]):
    print(all(dw[i] == 0))

True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
False
True
True
True
True
True
True
False
False
True
False
True
True
True
True


In [89]:
weight = torch.randn(5,50)
weight

tensor([[-4.4957e-01,  2.1680e-01,  3.6532e-02,  1.3700e+00, -8.3934e-01,
         -9.6162e-01,  9.1259e-01,  1.7254e+00,  1.6790e-01, -2.4011e+00,
          1.3005e-01, -2.8120e-01, -7.5087e-01, -2.4182e-01, -1.2076e+00,
          2.8364e-02, -9.6793e-01, -1.1261e+00,  1.0194e+00,  3.4209e-01,
         -3.5518e-01,  1.5220e+00,  2.8494e-02,  8.6401e-01, -6.2532e-01,
         -2.2515e-01,  1.8200e-01,  1.2736e+00, -7.9176e-01, -8.1006e-01,
          5.9936e-01,  2.0150e-01,  3.4870e-01, -7.2715e-01,  1.6827e+00,
          3.4853e-02, -1.9385e-03, -7.7006e-01, -1.2641e+00,  5.0987e-01,
          6.4353e-02,  6.9268e-01,  9.5261e-01,  4.4395e-01,  1.2023e+00,
          2.9555e-01, -1.1676e+00, -1.3143e+00, -3.6461e-01, -6.7640e-01],
        [-1.2703e+00,  1.5300e+00, -2.0593e+00,  5.7110e-01,  3.9554e-01,
         -1.1190e+00,  3.5127e-01,  2.8159e-01, -8.3668e-01,  1.1051e+00,
          1.8047e+00, -4.0001e-02, -1.9734e+00,  1.0110e-01,  6.4896e-01,
          2.1629e-01, -1.7893e-01,  6

In [94]:
torch.all(dw.eq(0)).item()

False

In [87]:
torch.div(weight, torch.sum(torch.abs(weight), 1, keepdim=True)) * 5

tensor([[-0.0750, -0.0659,  0.1320,  0.1435, -0.0688,  0.0262, -0.0769, -0.1994,
         -0.1166,  0.0098, -0.1041,  0.1088,  0.0585, -0.1910,  0.0021, -0.0785,
          0.1679,  0.1908, -0.2840,  0.0604, -0.1055, -0.0494,  0.1349, -0.2498,
         -0.0754, -0.1435, -0.0673,  0.0334,  0.0579, -0.3393,  0.0375,  0.0596,
         -0.0778, -0.0580,  0.0173,  0.1655, -0.3399, -0.0154, -0.1615, -0.1596,
          0.0527, -0.0030, -0.0835, -0.0687,  0.0158,  0.0944, -0.0145, -0.0005,
          0.0668,  0.0910],
        [ 0.0184, -0.0646, -0.1135,  0.0585, -0.1454, -0.1304, -0.0239, -0.3240,
          0.1236,  0.1327,  0.0969,  0.1153,  0.0286,  0.0611,  0.2156,  0.0278,
         -0.1200,  0.1340, -0.0464,  0.3510,  0.0796, -0.1210, -0.2023,  0.1360,
         -0.1890, -0.0431,  0.0749, -0.0200,  0.0132, -0.0239, -0.0959,  0.0388,
          0.0510,  0.0568,  0.0125, -0.1360, -0.2251,  0.0088,  0.0500,  0.0213,
          0.0083, -0.1452,  0.2215, -0.0533,  0.0345, -0.0430,  0.0902, -0.1524,


In [ ]:
import numpy as np

In [137]:
func = torch.load('weight_func.pth')
func

tensor([[0.1498, 0.0649, 0.1451,  ..., 0.0785, 0.0754, 0.1309],
        [0.0185, 0.0331, 0.1694,  ..., 0.0182, 0.1195, 0.0759],
        [0.1678, 0.0605, 0.1115,  ..., 0.1762, 0.0061, 0.0319],
        ...,
        [0.1818, 0.1116, 0.1698,  ..., 0.0421, 0.1005, 0.0321],
        [0.1000, 0.1403, 0.0358,  ..., 0.1692, 0.0101, 0.1853],
        [0.0467, 0.0972, 0.1152,  ..., 0.0786, 0.0507, 0.0739]],
       device='cuda:0', requires_grad=True)

In [155]:
origin = torch.load('weight_origin.pth')
origin

array([[0.15727054, 0.27909362, 0.15566394, ..., 0.25391203, 0.16233412,
        0.17020182],
       [0.0926707 , 0.04585999, 0.17958045, ..., 0.13925447, 0.2491092 ,
        0.15218142],
       [0.01297053, 0.17721987, 0.28220362, ..., 0.23663999, 0.22796502,
        0.01888497],
       ...,
       [0.23468051, 0.12437587, 0.02754973, ..., 0.11183273, 0.28429945,
        0.21705077],
       [0.06346631, 0.20911721, 0.04278182, ..., 0.2998066 , 0.10315044,
        0.25301037],
       [0.01345781, 0.23983217, 0.00309399, ..., 0.16053849, 0.28552143,
        0.19630527]])

In [156]:
w1 = torch.load('weight_1.pth')
w1 

array([[0.21139847, 0.06867376, 0.10596424, ..., 0.10892375, 0.29799877,
        0.1799474 ],
       [0.03545578, 0.03421535, 0.14775935, ..., 0.15234151, 0.14132225,
        0.01764962],
       [0.11830112, 0.0530921 , 0.26094672, ..., 0.21915892, 0.12271053,
        0.29676148],
       ...,
       [0.13807053, 0.08745527, 0.27102097, ..., 0.1196172 , 0.14406738,
        0.01601964],
       [0.20056866, 0.22563088, 0.06172917, ..., 0.22638941, 0.24253406,
        0.1360651 ],
       [0.02728711, 0.2144359 , 0.22457442, ..., 0.25904274, 0.28936001,
        0.1227374 ]])

In [177]:
w1= torch.load('C:\\Users\\admin\\Desktop\\ZJU\qian_dao_hu\\weight10\\parameters\\_parameters_dict.pt')
w1

{'autoname1<net>_connection3<con>:autoname1<net>_layer1<neg><-autoname1<net>_layer2<neg>:{weight}': tensor([[  -0., -120., -120.,  ..., -120., -120., -120.],
         [-120.,   -0., -120.,  ..., -120., -120., -120.],
         [-120., -120.,   -0.,  ..., -120., -120., -120.],
         ...,
         [-120., -120., -120.,  ...,   -0., -120., -120.],
         [-120., -120., -120.,  ..., -120.,   -0., -120.],
         [-120., -120., -120.,  ..., -120., -120.,   -0.]], device='cuda:0'),
 'autoname1<net>_connection1<con>:autoname1<net>_layer1<neg><-autoname1<net>_input<nod>:{weight}': tensor([[0.1056, 0.1481, 0.2086,  ..., 0.0280, 0.0529, 0.1309],
         [0.0188, 0.0928, 0.0564,  ..., 0.1054, 0.1436, 0.0663],
         [0.1406, 0.1335, 0.0690,  ..., 0.1774, 0.0646, 0.1819],
         ...,
         [0.1545, 0.0015, 0.1694,  ..., 0.0121, 0.1544, 0.1894],
         [0.1298, 0.1205, 0.1138,  ..., 0.1901, 0.1724, 0.1624],
         [0.0436, 0.1129, 0.0465,  ..., 0.0881, 0.0769, 0.1097]],
        dev

In [178]:
w500 = torch.load(r'C:\Users\admin\Desktop\ZJU\qian_dao_hu\weight2000\parameters\_parameters_dict.pt')
w500

{'autoname1<net>_connection3<con>:autoname1<net>_layer1<neg><-autoname1<net>_layer2<neg>:{weight}': tensor([[  -0., -120., -120.,  ..., -120., -120., -120.],
         [-120.,   -0., -120.,  ..., -120., -120., -120.],
         [-120., -120.,   -0.,  ..., -120., -120., -120.],
         ...,
         [-120., -120., -120.,  ...,   -0., -120., -120.],
         [-120., -120., -120.,  ..., -120.,   -0., -120.],
         [-120., -120., -120.,  ..., -120., -120.,   -0.]], device='cuda:0'),
 'autoname1<net>_connection1<con>:autoname1<net>_layer1<neg><-autoname1<net>_input<nod>:{weight}': tensor([[0.0427, 0.0505, 0.2436,  ..., 0.2574, 0.0504, 0.0395],
         [0.0219, 0.1826, 0.0406,  ..., 0.0356, 0.2015, 0.0194],
         [0.0847, 0.0598, 0.0670,  ..., 0.0571, 0.0420, 0.3436],
         ...,
         [0.0225, 0.1846, 0.0420,  ..., 0.0353, 0.2014, 0.0203],
         [0.0219, 0.1826, 0.0406,  ..., 0.0356, 0.2016, 0.0194],
         [0.0221, 0.1834, 0.0407,  ..., 0.0357, 0.2020, 0.0196]],
        dev