In [43]:
import csv
import pandas as pd
import random
import torch


In [ ]:
c = torch.load(f='save/ysc_model/parameters/_variable_dict.pt') # 这个是最全的一个输出
c

In [45]:
a = torch.randn(2,4)
a

tensor([[ 0.0958, -0.4020, -0.2788, -1.2050],
        [-0.9561, -1.0633, -1.8108,  1.0159]])

In [46]:
a * 0.1

tensor([[ 0.0096, -0.0402, -0.0279, -0.1205],
        [-0.0956, -0.1063, -0.1811,  0.1016]])

In [50]:
b = torch.tensor([0.,])
b

tensor([0.])

In [51]:
a * b

tensor([[0., -0., -0., -0.],
        [-0., -0., -0., 0.]])

In [16]:
input_node_num = 16
input_num_mul = 16 #  把输入维度放大10倍


In [ ]:
for key, val in c.items():
    print(key)
    print(val)

In [39]:
input_num_mul_index = 16
def ysc_create_data_after_pretrain_new_new(): # 这里在测试上可能要下一点功夫了, 当然要做到比训练数据集，更加的多样化， 如果有问题，就可能要 重新回去修改
                                              # 训练数据集的构建，之前做的确实太简单了
    rows = 400
    data = []
    groups = {
        'ANGRY': [15, 11],
        'NEGATIVE': [14, 7, 6, 5, 3, 1], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
        'POSITIVE': [2, 9, 10, 13],
        'NULL': [0, 4, 8, 12]
        }
    for _ in range(rows):
        selected_group = random.choice(list(groups.values()))
        result_list = [0.0] * input_node_num
        for i in range(input_node_num):
            if i in selected_group:
                result_list[i] = 1.0
            else:
                result_list[i] = random.uniform(0, 0.2)
        data.append(result_list * input_num_mul_index)
    with open('testdata.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(data)
    print("CSV文件已保存。")

In [40]:
ysc_create_data_after_pretrain_new_new()

CSV文件已保存。


In [41]:
input_node_num = 16
input_num_mul_index = 16 #  把输入维度放大10倍

# input_node_num = input_node_num * input_num_mul #  把输入维度放大10倍

def ysc_create_data_before_pretrain_new_new():
    rows = 10000
    data = []
    groups = {
        'ANGRY': [15, 11],
        'NEGATIVE': [14, 7, 6, 5, 3, 1], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
        'POSITIVE': [2, 9, 10, 13],
        'NULL': [0, 4, 8, 12]
        }
    for _ in range(rows):
        selected_group = random.choice(list(groups.values()))
        result_list = [0.0] * input_node_num
        for i in range(input_node_num):
            if i in selected_group:
                result_list[i] = 1.0
            else:
                result_list[i] = random.uniform(0, 0.2)
        data.append(result_list * input_num_mul_index)
    with open('output.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(data)
    print("CSV文件已保存。")


In [42]:
ysc_create_data_before_pretrain_new_new()

CSV文件已保存。


In [ ]:
df = pd.read_csv('output.csv', header=None) # 读取数据

In [26]:
def ysc_create_data_after_pretrain_new_new(): # 这里在测试上可能要下一点功夫了
    rows = 400
    data = []
    groups = {
        'ANGRY': [15, 11],
        'NEGATIVE': [14, 10, 7, 6, 5, 3, 1], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
        'POSITIVE': [2, 9, 10, 13],
        'NULL': [0, 4, 8, 12]
        }
    for _ in range(rows):
        selected_group = random.choice(list(groups.values()))
        result_list = [0.0] * input_node_num
        for i in range(input_node_num):
            if i in selected_group:
                result_list[i] = 1.0
            else:
                result_list[i] = random.uniform(0, 0.2)
        data.append(result_list * input_num_mul_index)
    with open('testdata.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(data)
    print("CSV文件已保存。")

In [27]:

ysc_create_data_after_pretrain_new_new()

CSV文件已保存。


In [ ]:
ls = [1,2,3,4,5,6]
ls2 = ls * 2

In [ ]:
ls2[0]= 100
ls2

In [ ]:
ysc_create_data_before_pretrain_new_new()


In [ ]:
buffer = torch.load('ysc_buffer.pth')

In [ ]:
torch.tensor(0).unsqueeze(0)

In [ ]:
avg_buffer = [sum(buffer[i][-100:]) / len(buffer[i][-100:]) for i in range(len(buffer))]

In [ ]:
buffer.shape

In [ ]:
len(buffer[1])

In [ ]:
buffer = torch.load('ysc_buffer.pth')
len(buffer)

In [ ]:
for i in range(4):
    print(len(buffer[i]))

In [ ]:
[sum(buffer[i][-200:]) / len(buffer[i][-200:]) for i in range(len(buffer))]

In [ ]:
ls = [[] for _ in range(4)]

In [ ]:
a = torch.randn(2,13)
b = torch.randn(2,13)
a / b

In [ ]:
import numpy as np

In [ ]:
np.random.rand(10, 4) * 0.2

In [ ]:
a = torch.load('weight_origin.pth')

In [ ]:
a


In [ ]:
b = torch.load('weight_new.pth')

In [ ]:
b

In [ ]:
a[0][9]

In [ ]:
b[0][9]

In [ ]:
for i in range(c.shape[0]):
    if all(c[i]) :
        pass
    else:
        print(i)

In [ ]:
all(c[10])
c[10]

In [ ]:
ls1 = [1,2,3,4]
ls2 = [1,2,3,4]

In [ ]:
torch.tensor(ls1) / torch.tensor(ls2)

In [ ]:
dw = torch.load('dw.pth')
dw

In [ ]:
dw = torch.load('dw.pth')
for i  in range(dw.shape[0]):
    print(all(dw[i] == 0))

In [ ]:
weight = torch.randn(5,50)
weight

In [ ]:
torch.all(dw.eq(0)).item()

In [ ]:
torch.div(weight, torch.sum(torch.abs(weight), 1, keepdim=True)) * 5

In [ ]:
import numpy as np

In [ ]:
func = torch.load('weight_func.pth')
func

In [ ]:
origin = torch.load('weight_origin.pth')
origin

In [ ]:
w1 = torch.load('weight_1.pth')
w1 

In [ ]:
w1= torch.load('C:\\Users\\admin\\Desktop\\ZJU\qian_dao_hu\\weight10\\parameters\\_parameters_dict.pt')
w1

In [ ]:
w500 = torch.load(r'C:\Users\admin\Desktop\ZJU\qian_dao_hu\save_all_new\parameters\_variables.pt')
w500

In [ ]:
w500 = torch.load(r'C:\Users\admin\Desktop\ZJU\qian_dao_hu\save_all\parameters\_variables.pt')
w500

In [ ]:
from ysc_stdp import YscNet
from SPAIC import spaic

In [14]:
emo = YscNet()

net_loaded = spaic.Network_loader.network_load(filename='save_all')

In [15]:
print(net_loaded.connection1.weight.value)

tensor([[0.0552, 0.1087, 0.1285,  ..., 0.1180, 0.0865, 0.1126],
        [0.1809, 0.1212, 0.0795,  ..., 0.1242, 0.0411, 0.0114],
        [0.0686, 0.1643, 0.0426,  ..., 0.0722, 0.1724, 0.0107],
        ...,
        [0.0576, 0.0744, 0.2521,  ..., 0.2369, 0.0487, 0.0743],
        [0.0634, 0.1988, 0.0629,  ..., 0.0537, 0.1401, 0.0315],
        [0.0833, 0.2066, 0.0843,  ..., 0.0628, 0.1870, 0.0228]],
       requires_grad=True)


In [ ]:
# spaic.Network_saver.network_save(net_loaded, filename='save_all_new', save=True, combine=False)